[package]
name = "remule"
version = "0.1.0"
authors = ["Cody Schafer <dev@codyps.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
fmt-extra = "0.2.1"
plain = "0.2.3"
async-std = { version = "1.5.0", features = ["attributes", "unstable"]}
enum-primitive-derive = "0.1.2"
num-traits = "0.2"
md5 = "0.7"
arc4 = "0.1"
futures = "0.3.4"
rand = "0.7.3"
