[package]
name = "emule-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
fmt-extra = "0.2.1"
plain = "0.2"
num-traits = "0.2"
enum-primitive-derive = "0.2"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
bytes = "1"
flate2 = "1"
