[package]
name = "emule-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33.3"
fmt-extra = "0.2.1"
plain = "0.2.3"
num-traits = "0.2"
enum-primitive-derive = "0.2.1"
thiserror = "*"
serde = { version = "*", features = ["derive"] }
